global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets: ["localhost:9090"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: prometheus
        
  - job_name: cadvisor-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus-cadvisor-exporter:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: ^(.*):(.*)$
        replacement: ${1}

  - job_name: node-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus-node-exporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: ^(.*):(.*)$
        replacement: ${1}

  - job_name: fastcom-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus-fastcom-exporter:9877"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: ^(.*):(.*)$
        replacement: ${1}

  - job_name: speedtest-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus-speedtest-exporter:9876"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: ^(.*):(.*)$
        replacement: ${1}

  - job_name: blackbox-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus-blackbox-exporter:9115"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: ^(.*):(.*)$
        replacement: ${1}

  - job_name: blackbox-probes
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - grafana:3000
        - plex:32400/web/index.html
        - portainer:9000
        - prometheus:9090
        - prometheus-cadvisor-exporter:8080
        - prometheus-node-exporter:9100
        - prometheus-fastcom-exporter:9877
        - prometheus-speedtest-exporter:9876
        - transmission:9091
        - traefik:8080

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        regex: ^(.*):(.*)$
        replacement: ${1}-probe
      - target_label: __address__
        replacement: prometheus-blackbox-exporter:9115 # The blackbox exporter's real hostname:port