global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: cadvisor-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["cadvisor-exporter:8080"]

  - job_name: node-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: fastcom-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["fastcom-exporter:9877"]

  - job_name: speedtest-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["speedtest-exporter:9876"]