auth:
  - user: ${USER}
    group: ${GROUP}
    uid: ${PUID}
    gid: ${PGID}
    password: ${PASSWORD}

share:
  - name: public
    path: /data/shares/public
    guestok: yes
    readonly: no
    browsable: yes
    veto: no
    recycle: no
    hidefiles: /_*/

  - name: foo
    path: /data/shares/${USER}
    writelist: foo
    validusers: foo
    guestok: no
    readonly: no
    browsable: yes
    veto: no
    recycle: yes
    hidefiles: /_*/
