auth:
  - user: ${USER}
    group: ${GROUP}
    uid: ${UID}
    gid: ${GID}
    password: ${PASSWORD}

share:
  - name: public
    path: /data/shares/public
    guestok: yes
    readonly: no
    browsable: yes
    veto: no
    recycle: no
    hidefiles: /_*/

  - name: ${USER}
    path: /data/shares/${USER}
    writelist: ${USER}
    validusers: ${USER}
    guestok: no
    readonly: no
    browsable: yes
    veto: no
    recycle: yes
    hidefiles: /_*/
