---
support_services: []
services: []

container_default_opts:
  # user: "{{ PUID }}"
  pull: true
  state: started 
  restart_policy: unless-stopped
  env: {}
  ports: []
  command: []
  volumes: []
  links: []
  labels: {}