---
support_services: []
services: []

service_default_config:
  configs: []
  folders: ["."]
  replace: []

container_default_opts:
  # user: "{{ PUID }}"
  pull: true
  state: started
  restart_policy: unless-stopped
  networks:
    - name: "{{ ansible_facts.nodename }}"
  env: {}
  ports: []
  command: []
  volumes: []
  labels: {}
