---
services: []

container_default_opts:
  pull: true
  version: latest
  recreate: true
  auto_remove: true
  restart_policy: unless-stopped
  command_handling: correct
  env: {}
  ports: []
  command: []
  volumes: []
  labels: {}