---
services: []

container_default_opts:
  user: "{{ PUID }}:{{ PGID }}"
  pull: true
  state: started 
  restart_policy: unless-stopped
  env: {}
  ports: []
  command: []
  volumes: []
  links: []
  labels: {}