---
grafana:
  name: grafana
  image: grafana/grafana:latest
  env: 
    GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
  ports:
    - 3000:3000
  volumes:
    - "grafana_data:/var/lib/grafana" # database and plugins
  links:
    - prometheus
  labels:
    traefik.enable: "true"
    traefik.http.routers.grafana.entrypoints: "http"
    traefik.http.routers.grafana.rule: "Host(`grafana.{{ ansible_facts.nodename }}.local`)"
    traefik.http.routers.grafana.service: "grafana@docker"
    traefik.http.services.grafana.loadbalancer.server.port: "3000"