---
TZ: "{{ remote_envfile['TZ'] }}"
PUID: "{{ remote_envfile['PUID'] }}"
PGID: "{{ remote_envfile['PGID'] }}"

services_path: "{{ ansible_env.PWD }}"
services_configs_path: "{{ remote_envfile['HOMESERVER_PATH'] }}/config"

# services that can use configs from a local copy or
# store config/data in mounted volumes
#
services_configs:
  - name: traefik
    configs:
      - src: traefik/traefik.yml
        dest: traefik/traefik.yml

  - name: prometheus
    folders:
      - config
      - data
    configs:
      - src: prometheus/prometheus.yml
        dest: prometheus/config/prometheus.yml
    replace:
      - file: prometheus/config/prometheus.yml
        search: "watchtower_api_key"
        value: "    bearer_token: {{ remote_envfile['WATCHTOWER_HTTP_API_TOKEN'] }}"

  - name: grafana
    folders:
      - data

  - name: portainer
    folders:
      - data

  - name: transmission
    configs:
      - src: transmission/settings.json
        dest: transmission/settings.json

  - name: plex
    folders:
      - config
      - media
      - transcode

# prometheus exporters and other support services
#
support_services:
  - watchtower
  - prometheus-blackbox-exporter
  - prometheus-cadvisor-exporter
  - prometheus-node-exporter
  - prometheus-fastcom-exporter
  - prometheus-speedtest-exporter

services:
  - prometheus
  - grafana
  - plex
  - transmission
  - portainer
  - traefik
