---
TZ: "{{ remote_envfile['TZ'] }}"
PUID: "{{ remote_envfile['PUID'] }}"
PGID: "{{ remote_envfile['PGID'] }}"

services_path: "{{ ansible_env.PWD }}"
services_configs_path: "{{ remote_envfile['HOMESERVER_PATH'] }}/config"

# This is a list of services.
# services_configs:
#   Each service is represented as a map with the following properties:
#
#   The name of the service. This is a string that identifies the service.
#   name: <service-name>
#
#   This is a list of folders that should be created inside the service folder.
#   Folder permissions are set to 0777.
#   folders:
#     - <folder-name>
#
#   This is a list of configuration files for the service.
#   configs:
#     Each configuration file is represented as a map with the following properties:
#
#     The source path of the configuration file. This is a string that specifies where the configuration file is located in your local system.
#     src: <path-on-local>
#
#     The destination path of the configuration file. This is a string that specifies where the configuration file should be copied to in the remote system.
#     dest: <path-on-remote>
#
#   This is a list of files in which a specific string should be replaced with a value.
#   replace:
#     Each item in the list is a map with the following properties:
#
#     The path of the file in which the replacement should be made.
#     file: <path-on-remote>
#
#     The string that should be replaced. This is a string.
#     search: <string>
#
#     The string that should replace the search string. This is a string.
#     value: <string>
services_configs:
  - name: avahi
    configs:
      - src: avahi/smb.service
        dest: avahi/smb.service

  - name: traefik
    configs:
      - src: traefik/traefik.yml
        dest: traefik/traefik.yml

  - name: blackbox
    folders:
      - config
    configs:
      - src: blackbox/config.yml
        dest: blackbox/config.yml

  - name: prometheus
    folders:
      - config
      - data
    configs:
      - src: prometheus/prometheus.yml
        dest: prometheus/config/prometheus.yml
    replace:
      - file: prometheus/config/prometheus.yml
        search: "watchtower_api_key"
        value: "    bearer_token: {{ remote_envfile['WATCHTOWER_HTTP_API_TOKEN'] }}"

  - name: samba
    folders:
      - shares
    configs:
      - src: samba/config.yml
        dest: samba/config.yml

  - name: grafana
    folders:
      - data

  - name: portainer
    folders:
      - data

  - name: transmission
    configs:
      - src: transmission/settings.json
        dest: transmission/settings.json

  - name: plex
    folders:
      - config
      - media
      - transcode

  - name: homeassistant
    folders:
      - config
    configs:
      - src: homeassistant/binary_sensors.yml
        dest: homeassistant/config/binary_sensors.yaml

# prometheus exporters and other support services
#
support_services:
  - prometheus-blackbox-exporter
  - prometheus-cadvisor-exporter
  - prometheus-fastcom-exporter
  - prometheus-node-exporter
  - prometheus-speedtest-exporter
  - watchtower

services:
  - avahi
  - grafana
  - homeassistant
  - plex
  - portainer
  - prometheus
  - samba
  - traefik
  - transmission
