---
TZ: "{{ remote_envfile['TZ'] }}"
PUID: "{{ remote_envfile['PUID'] }}"
PGID: "{{ remote_envfile['PGID'] }}"

services_path: "{{ ansible_env.HOME }}/services"
services_configs_path: "{{ remote_envfile['HOMESERVER_PATH'] }}/config"

# prometheus exporters and other support services
#
support_services:
  - prometheus-node-exporter
  - prometheus-fastcom-exporter
  - prometheus-speedtest-exporter

services:
  - prometheus
  - grafana
  - whoami
  - portainer
  - traefik