---
plex:
  name: plex
  image: plexinc/pms-docker:latest
  env:
    TZ: "{{ TZ }}"
    PLEX_UID: "{{ PUID }}"
    PLEX_GID: "{{ PGID }}"
    HOSTNAME: "{{ ansible_facts.nodename }}"
    PLEX_CLAIM: "{{ remote_envfile['PLEX_CLAIM'] }}" # https://www.plex.tv/claim/
    ADVERTISE_IP: "http://plex.{{ ansible_facts.nodename }}.local"
  volumes:
    - "~/plex/config:/config"
    - "~/plex/media:/media"
    - "~/plex/transcode:/transcode"
  ports:
    - 32400:32400
    - 1900:1900/udp
    - 8324:8324
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
    - 32469:32469
  labels:
    traefik.enable: "true"
    traefik.http.routers.plex.entrypoints: "http"
    traefik.http.routers.plex.rule: "Host(`plex.{{ ansible_facts.nodename }}.local`)"
    traefik.http.routers.plex.service: "plex@docker"
    traefik.http.services.plex.loadbalancer.server.port: "32400"