---
prometheus:
  name: prometheus
  image: prom/prometheus:latest
  user: "{{ PUID }}:{{ PGID }}"
  ports:
    - 9090:9090
  volumes:
    - "{{ services_path }}/prometheus/data:/prometheus"
    - "{{ services_path }}/prometheus/config:/etc/prometheus"
  links:
    - "prometheus-cadvisor-exporter:cadvisor-exporter"
    - "prometheus-node-exporter:node-exporter"
    - "prometheus-fastcom-exporter:fastcom-exporter"
    - "prometheus-speedtest-exporter:speedtest-exporter"
  labels:
    traefik.enable: "true"
    traefik.http.routers.prometheus.entrypoints: "http"
    traefik.http.routers.prometheus.rule: "Host(`prometheus.{{ ansible_facts.nodename }}.local`)"
    traefik.http.routers.prometheus.service: "prometheus@docker"
    traefik.http.services.prometheus.loadbalancer.server.port: "9090"