---
prometheus:
  name: prometheus
  image: prom/prometheus:latest
  command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--storage.tsdb.retention.time={{ remote_envfile['PROMETHEUS_TSDB_RETENTION_TIME'] }}"
    - "--web.console.templates=/etc/prometheus/consoles"
    - "--web.console.libraries=/etc/prometheus/console_libraries"
  ports:
    - 9090:9090
  volumes:
    - "{{ services_path }}/prometheus/data:/prometheus"
    - "{{ services_path }}/prometheus/config:/etc/prometheus"
  labels:
    traefik.enable: "true"
    traefik.http.routers.prometheus.entrypoints: "http"
    traefik.http.routers.prometheus.rule: "Host(`prometheus.{{ ansible_facts.nodename }}.local`)"
    traefik.http.routers.prometheus.service: "prometheus@docker"
    traefik.http.services.prometheus.loadbalancer.server.port: "9090"
