---
prometheus:
  name: prometheus
  image: prom/prometheus:latest
  ports:
    - 9090:9090
  volumes:
    - "prometheus_data:/prometheus"
    - "{{ services_configs_path }}/prometheus:/etc/prometheus"
  links:
    - "prometheus-fastcom-exporter:fastcom-exporter"
    - "prometheus-speedtest-exporter:speedtest-exporter"
  labels:
    traefik.enable: "true"
    traefik.http.routers.prometheus.entrypoints: "http"
    traefik.http.routers.prometheus.rule: "Host(`prometheus.{{ ansible_facts.nodename }}.local`)"
    traefik.http.routers.prometheus.service: "prometheus@docker"
    traefik.http.services.prometheus.loadbalancer.server.port: "9090"