---
prometheus:
  name: prometheus
  image: prom/prometheus:latest
  ports:
    - "9090:9090"
  volumes:
    - "prometheus_data:/prometheus"
    - "{{ services_configs_path }}/prometheus:/etc/prometheus"
  labels:
    traefik.enabled: "true"