---
prometheus-node-exporter:
  name: prometheus-node-exporter
  image: prom/node-exporter:latest
  command:
    - "--path.procfs=/host/proc"
    - "--path.rootfs=/rootfs"
    - "--path.sysfs=/host/sys"
    - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    - "--collector.systemd"
    - "--collector.processes"
  ports:
    - 9100:9100
  volumes:
    - "/proc:/host/proc:ro"
    - "/sys:/host/sys:ro"
    - "/:/rootfs:ro"