---
samba:
  name: samba
  image: crazymax/samba:latest
  env:
    TZ: "{{ TZ }}"
    UID: "{{ PUID }}"
    GID: "{{ PGID }}"
    USER: "emaiax"
    GROUP: "emaiax"
    PASSWORD: "{{ lookup('onepassword', 'ansible', field='samba-passwd') }}"
    SAMBA_LOG_LEVEL: "1"
  networks:
    - name: host
  volumes:
    - "{{ services_path }}/samba/shares:/data/shares"
    - "{{ services_path }}/samba/config.yml:/data/config.yml"
