---
traefik:
  name: traefik
  image: traefik:latest
  ports:
    - 80:80
    - 443:443
    - 8080:8080
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock # so that Traefik can listen to the Docker events
    - "{{ services_path }}/traefik/config:/etc/traefik"
  labels:
    traefik.enable: "true"
    traefik.http.routers.api.entrypoints: "http"
    traefik.http.routers.api.rule: "Host(`traefik.{{ ansible_facts.nodename }}.local`)"
    traefik.http.routers.api.service: "api@internal"
    traefik.http.services.traefik.loadbalancer.server.port: "80"