---
transmission:
  name: transmission
  image: linuxserver/transmission:latest
  env: 
    TZ: "{{ TZ }}"
    PUID: "{{ PUID }}"
    PGID: "{{ PGID }}"
  ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp
  volumes:
    - "{{ services_path }}/Downloads:/downloads"
    - "{{ services_path }}/transmission:/config"
  labels:
    traefik.enable: "true"
    traefik.http.routers.transmission.entrypoints: "http"
    traefik.http.routers.transmission.rule: "Host(`transmission.{{ ansible_facts.nodename }}.local`)"
    traefik.http.routers.transmission.service: "transmission@docker"
    traefik.http.services.transmission.loadbalancer.server.port: "9091"