- name: Install docker and docker-compose
  tags: docker, docker-daemon
  become: true
  package:
    name:
      - docker
      - docker-compose
    state: latest
    update_cache: yes

- name: Ensure docker daemon state
  tags: docker, docker-daemon
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Create bridge network "{{ ansible_facts.nodename }}"
  tags: docker, docker-network
  community.docker.docker_network:
    name: "{{ ansible_facts.nodename }}"

- name: Create bridget network "dockerlan"
  tags: docker, docker-network
  community.docker.docker_network:
    name: dockerlan
    ipam_config:
      - subnet: 192.168.168.0/26
        gateway: 192.168.168.1
        iprange: 192.168.168.0/26

- name: Add user to docker group
  tags: docker, docker-daemon
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true
