---
- name: Deploy services
  tags: deploy-services
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}"
    hostname: "{{ service.hostname | default('') }}"
    capabilities: "{{ service.capabilities | default([]) }}"
    state: started
    command_handling: correct
    recreate: "{{ service.recreate | default(false) }}"
    restart_policy: "{{ service.restart_policy }}"
    env: "{{ service.env }}"
    command: "{{ service.command }}"
    networks: "{{ service.networks }}"
    ports: "{{ service.ports }}"
    volumes: "{{ service.volumes }}"
    labels: "{{ service.labels }}"
  with_items: "{{ docker_support_services | union(docker_services) }}"
  vars:
    service: "{{ container_default_opts | combine(lookup('vars', item)) }}"
  notify:
    - clean_avahi_aliases
    - update_avahi_aliases
