---
- name: Find services to deploy
  tags: deploy-services
  include_vars: "{{ item }}.yml"
  with_items: "{{ support_services | union(services) }}"

- name: Register services to deploy and alias
  tags: deploy-services
  set_fact:
    docker_support_services: "{{ support_services }}"
    docker_services: "{{ services }}"

- name: Create services folders
  tags: deploy-services, deploy-local-config
  ansible.builtin.file:
    path: "{{ services_path }}/{{ item }}/config"
    owner: "{{ PUID }}"
    group: "{{ PGID }}"
    state: directory
  with_items: "{{ configurable_services }}"

- name: Copy config files to services folders
  tags: deploy-services
  ansible.builtin.copy:
    src: "{{ services_configs_path }}/{{ item }}/{{ item }}.yml"
    dest: "{{ services_path }}/{{ item }}/config/{{ item }}.yml"
    owner: "{{ PUID }}"
    group: "{{ PGID }}"
    force: yes
    remote_src: true
  with_items: "{{ configurable_services }}"

- name: Override services config files with local copy
  tags: never, deploy-local-config
  ansible.builtin.copy:
    src: "./config/{{ item }}/{{ item }}.yml"
    dest: "{{ services_path }}/{{ item }}/config/{{ item }}.yml"
    owner: "{{ PUID }}"
    group: "{{ PGID }}"
    force: yes
  with_items: "{{ configurable_services }}"

- name: Deploy services
  tags: deploy-services
  docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}"
    state: started
    command_handling: correct
    recreate: "{{ service.recreate | default(false) }}"
    restart_policy: "{{ service.restart_policy }}"
    env: "{{ service.env }}"
    ports: "{{ service.ports }}"
    command: "{{ service.command }}"
    volumes: "{{ service.volumes }}"
    links: "{{ service.links }}"
    labels: "{{ service.labels }}"
  with_items: "{{ docker_support_services | union(docker_services) }}"
  vars:
    service: "{{ container_default_opts | combine(lookup('vars', item)) }}"
  notify:
    - clean_avahi_aliases
    - update_avahi_aliases

- name: "[DEBUG] Services configs to deploy"
  tags: never, debug
  debug:
    msg: "{{ service }}"
  with_items: "{{ docker_support_services | union(docker_services) }}"
  vars:
    service: "{{ container_default_opts | combine(lookup('vars', item)) }}"