---
- import_tasks: find.yml
- import_tasks: config.yml
- import_tasks: deploy.yml

- name: "[DEBUG] Services configs to deploy"
  tags: never, debug
  debug:
    msg: "{{ service }}"
  with_items: "{{ docker_support_services | union(docker_services) }}"
  vars:
    service: "{{ container_default_opts | combine(lookup('vars', item)) }}"
